-- MySQL Script generated by MySQL Workbench
-- Mon Oct 28 09:06:01 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ead_faculdade
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ead_faculdade` ;

-- -----------------------------------------------------
-- Schema ead_faculdade
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ead_faculdade` DEFAULT CHARACTER SET utf8 ;
USE `ead_faculdade` ;

-- -----------------------------------------------------
-- Table `ead_faculdade`.`tbl_aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ead_faculdade`.`tbl_aluno` ;

CREATE TABLE IF NOT EXISTS `ead_faculdade`.`tbl_aluno` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `dtnascimento` DATE NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `ead_faculdade`.`tbl_aluno` (`id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ead_faculdade`.`tbl_aluno_telefone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ead_faculdade`.`tbl_aluno_telefone` ;

CREATE TABLE IF NOT EXISTS `ead_faculdade`.`tbl_aluno_telefone` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `telefone` VARCHAR(45) NOT NULL,
  `id_aluno` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tbl_aluno_telefone_tbl_aluno`
    FOREIGN KEY (`id_aluno`)
    REFERENCES `ead_faculdade`.`tbl_aluno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `ead_faculdade`.`tbl_aluno_telefone` (`id` ASC) VISIBLE;

CREATE INDEX `fk_tbl_aluno_telefone_tbl_aluno_idx` ON `ead_faculdade`.`tbl_aluno_telefone` (`id_aluno` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ead_faculdade`.`tbl_aluno_endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ead_faculdade`.`tbl_aluno_endereco` ;

CREATE TABLE IF NOT EXISTS `ead_faculdade`.`tbl_aluno_endereco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(100) NOT NULL,
  `complemento` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(9) NOT NULL,
  `id_aluno` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tbl_aluno_endereco_tbl_aluno1`
    FOREIGN KEY (`id_aluno`)
    REFERENCES `ead_faculdade`.`tbl_aluno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `ead_faculdade`.`tbl_aluno_endereco` (`id` ASC) VISIBLE;

CREATE INDEX `fk_tbl_aluno_endereco_tbl_aluno1_idx` ON `ead_faculdade`.`tbl_aluno_endereco` (`id_aluno` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ead_faculdade`.`tbl_curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ead_faculdade`.`tbl_curso` ;

CREATE TABLE IF NOT EXISTS `ead_faculdade`.`tbl_curso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `ead_faculdade`.`tbl_curso` (`id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ead_faculdade`.`tbl_professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ead_faculdade`.`tbl_professor` ;

CREATE TABLE IF NOT EXISTS `ead_faculdade`.`tbl_professor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `dtnascimento` DATE NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `ead_faculdade`.`tbl_professor` (`id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ead_faculdade`.`tbl_materia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ead_faculdade`.`tbl_materia` ;

CREATE TABLE IF NOT EXISTS `ead_faculdade`.`tbl_materia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `id_professor` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tbl_materia_tbl_professor1`
    FOREIGN KEY (`id_professor`)
    REFERENCES `ead_faculdade`.`tbl_professor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `ead_faculdade`.`tbl_materia` (`id` ASC) VISIBLE;

CREATE INDEX `fk_tbl_materia_tbl_professor1_idx` ON `ead_faculdade`.`tbl_materia` (`id_professor` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ead_faculdade`.`tbl_aluno_nota`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ead_faculdade`.`tbl_aluno_nota` ;

CREATE TABLE IF NOT EXISTS `ead_faculdade`.`tbl_aluno_nota` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nota` INT NULL,
  `id_aluno` INT NOT NULL,
  `id_curso` INT NOT NULL,
  `id_materia` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tbl_aluno_nota_tbl_aluno1`
    FOREIGN KEY (`id_aluno`)
    REFERENCES `ead_faculdade`.`tbl_aluno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_aluno_nota_tbl_curso1`
    FOREIGN KEY (`id_curso`)
    REFERENCES `ead_faculdade`.`tbl_curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_aluno_nota_tbl_materia1`
    FOREIGN KEY (`id_materia`)
    REFERENCES `ead_faculdade`.`tbl_materia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `ead_faculdade`.`tbl_aluno_nota` (`id` ASC) VISIBLE;

CREATE INDEX `fk_tbl_aluno_nota_tbl_aluno1_idx` ON `ead_faculdade`.`tbl_aluno_nota` (`id_aluno` ASC) VISIBLE;

CREATE INDEX `fk_tbl_aluno_nota_tbl_curso1_idx` ON `ead_faculdade`.`tbl_aluno_nota` (`id_curso` ASC) VISIBLE;

CREATE INDEX `fk_tbl_aluno_nota_tbl_materia1_idx` ON `ead_faculdade`.`tbl_aluno_nota` (`id_materia` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ead_faculdade`.`tbl_curso_aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ead_faculdade`.`tbl_curso_aluno` ;

CREATE TABLE IF NOT EXISTS `ead_faculdade`.`tbl_curso_aluno` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_curso` INT NOT NULL,
  `id_aluno` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tbl_curso_aluno_tbl_curso1`
    FOREIGN KEY (`id_curso`)
    REFERENCES `ead_faculdade`.`tbl_curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_curso_aluno_tbl_aluno1`
    FOREIGN KEY (`id_aluno`)
    REFERENCES `ead_faculdade`.`tbl_aluno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `ead_faculdade`.`tbl_curso_aluno` (`id` ASC) VISIBLE;

CREATE INDEX `fk_tbl_curso_aluno_tbl_curso1_idx` ON `ead_faculdade`.`tbl_curso_aluno` (`id_curso` ASC) VISIBLE;

CREATE INDEX `fk_tbl_curso_aluno_tbl_aluno1_idx` ON `ead_faculdade`.`tbl_curso_aluno` (`id_aluno` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ead_faculdade`.`tbl_curso_materia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ead_faculdade`.`tbl_curso_materia` ;

CREATE TABLE IF NOT EXISTS `ead_faculdade`.`tbl_curso_materia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_curso` INT NOT NULL,
  `id_materia` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tbl_curso_materia_tbl_curso1`
    FOREIGN KEY (`id_curso`)
    REFERENCES `ead_faculdade`.`tbl_curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_curso_materia_tbl_materia1`
    FOREIGN KEY (`id_materia`)
    REFERENCES `ead_faculdade`.`tbl_materia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `ead_faculdade`.`tbl_curso_materia` (`id` ASC) VISIBLE;

CREATE INDEX `fk_tbl_curso_materia_tbl_curso1_idx` ON `ead_faculdade`.`tbl_curso_materia` (`id_curso` ASC) VISIBLE;

CREATE INDEX `fk_tbl_curso_materia_tbl_materia1_idx` ON `ead_faculdade`.`tbl_curso_materia` (`id_materia` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ead_faculdade`.`tbl_professor_tel...`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ead_faculdade`.`tbl_professor_tel...` ;

CREATE TABLE IF NOT EXISTS `ead_faculdade`.`tbl_professor_tel...` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `telefone` VARCHAR(45) NOT NULL,
  `id_professor` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tbl_professor_tel..._tbl_professor1`
    FOREIGN KEY (`id_professor`)
    REFERENCES `ead_faculdade`.`tbl_professor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `ead_faculdade`.`tbl_professor_tel...` (`id` ASC) VISIBLE;

CREATE INDEX `fk_tbl_professor_tel..._tbl_professor1_idx` ON `ead_faculdade`.`tbl_professor_tel...` (`id_professor` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ead_faculdade`.`tbl_professor_endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ead_faculdade`.`tbl_professor_endereco` ;

CREATE TABLE IF NOT EXISTS `ead_faculdade`.`tbl_professor_endereco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(100) NOT NULL,
  `complemento` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `pais` VARCHAR(45) NULL,
  `cep` VARCHAR(9) NOT NULL,
  `id_professor` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tbl_professor_endereco_tbl_professor1`
    FOREIGN KEY (`id_professor`)
    REFERENCES `ead_faculdade`.`tbl_professor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `ead_faculdade`.`tbl_professor_endereco` (`id` ASC) VISIBLE;

CREATE INDEX `fk_tbl_professor_endereco_tbl_professor1_idx` ON `ead_faculdade`.`tbl_professor_endereco` (`id_professor` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
